name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo clippy --locked -- --deny=warnings
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/cache/blob/master/examples.md#rust---cargo
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          sudo apt-get install --no-install-recommends --yes musl-tools
          rustup target add x86_64-unknown-linux-musl
          cargo build --locked --release --target=x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v4
        with:
          name: openai-proxy
          path: target/release/openai-proxy
  docker:
    if: github.ref == 'refs/heads/main'
    needs:
      - cargo-build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: openai-proxy
      - run: |
          chmod +x openai-proxy

          cat << 'EOD' > Dockerfile
          FROM alpine
          COPY openai-proxy /usr/local/bin/
          ENTRYPOINT ["/usr/local/bin/openai-proxy"]
          EOD
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hakuyume/openai-proxy:${{ github.sha }}
            ghcr.io/hakuyume/openai-proxy
